#spring.application.name=Journal App
#spring.data.mongodb.host=localhost
spring.data.mongodb.database=journaldb
spring.data.mongodb.uri=mongodb+srv://Nikhil:Nikhil@cluster0.7j8jov8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.port=27017
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE
